name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Check formatting
        run: |
          out=$(gofmt -l . | grep -v '^vendor/' || true)
          if [ -n "$out" ]; then
            echo "Unformatted files:" >&2
            echo "$out" | sed 's/^/  - /' >&2
            exit 1
          fi
      - name: Vet
        run: go vet ./...
