name: Postgres Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pg-int:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gpsnav
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Wait for Postgres to be available
        shell: bash
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && break
            sleep 1
          done
          echo "Postgres port open"

      - name: Run Postgres integration tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/gpsnav?sslmode=disable
        run: go test -tags postgres_integration ./internal/store -v

