name: Smoke

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Build
        run: go build ./...
      - name: Run smoke script
        env:
          PORT: '8080'
        run: |
          chmod +x scripts/smoke.sh
          ./scripts/smoke.sh
